// Generated by skywork-cli website image import. Do not edit by hand.
export const IMAGES = {
  CARRIER_DOT_PROFILE: "/images/img_a965b3009fc8.png",
  HOME_DOT_APPLIANCES: "/images/img_8bcb5bcb41cd.jpg",
  HOME_DOT_FURNITURE: "/images/img_5dba682ce23a.jpg",
  HOME_DOT_HERO: "/images/img_003d4a77916c.jpg",
} as const;
