type LegalDocument = "privacy" | "cookies" | "terms" | "impressum";
type Language = "en" | "hr";

const operator = {
  name: "Legal Name",
  address: "Legal address",
  registration: "Legal Registration",
  vatId: "11111111111",
  privacyEmail: "example@van-scout.com",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section><h2>{title}</h2>{children}</section>;
}

function Privacy({ language }: { language: Language }) {
  if (language === "hr") return <>
    <Section title="1. Voditelj obrade"><p>Voditelj obrade je {operator.name}, {operator.address}, registracijski broj {operator.registration}, OIB/PDV ID {operator.vatId}. Za pitanja i ostvarivanje prava obratite se na <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a>.</p></Section>
    <Section title="2. Podaci koje obrađujemo"><p>Obrađujemo podatke računa i identiteta, e-mail i potvrđeni telefonski broj; podatke o zahtjevima za prijevoz, adrese, koordinate, fotografije i upute; ponude, cijene i poruke; podatke o kupnji kredita i Stripe identifikatore; te sigurnosne i tehničke zapise potrebne za rad usluge. Ne unosite osjetljive podatke u poruke.</p></Section>
    <Section title="3. Svrhe i pravne osnove"><ul><li>otvaranje računa, povezivanje korisnika i prijevoznika, ponude, razgovori i izvršenje prijevoza: izvršavanje ugovora ili radnje prije sklapanja ugovora;</li><li>računovodstvene, porezne i regulatorne obveze: pravna obveza;</li><li>sprječavanje prijevare, sigurnost, rješavanje sporova i poboljšanje pouzdanosti: legitimni interesi, nakon procjene nužnosti i ravnoteže;</li><li>neobavezne marketinške ili slične aktivnosti: privola, ako ih uvedemo.</li></ul></Section>
    <Section title="4. Tko vidi i prima podatke"><p>Sudionici konkretnog prijevoza vide podatke potrebne za ponudu i razgovor. Kontaktni podaci druge strane otkrivaju se nakon potvrde prijevoza. Pružatelji koji mogu obrađivati podatke uključuju Vercel (hosting), Neon/AWS (baza), Ably (obavijesti u stvarnom vremenu), Google i Firebase (prijava i potvrda telefona), Stripe (plaćanja), Zoho (e-mail) i Geoapify (lokacije). Sa svakim primjenjivim izvršiteljem obrade moramo imati ugovor iz članka 28. GDPR-a.</p></Section>
    <Section title="5. Međunarodni prijenosi"><p>Produkcijska baza smještena je u Europskoj uniji, a neki pružatelji ili njihovi podizvršitelji mogu obrađivati podatke izvan EGP-a. Za takve prijenose primjenjujemo odluku o primjerenosti kada je primjenjiva ili odgovarajuće zaštitne mjere iz članka 46. GDPR-a, uključujući standardne ugovorne klauzule i potrebne dodatne mjere. Kopiju relevantnih zaštitnih mjera možete zatražiti na adresi za privatnost.</p></Section>
    <Section title="6. Čuvanje i brisanje"><p>Poruke i tekst ponuda automatski se brišu nakon 730 dana. Podatke računa čuvamo dok je račun aktivan, a brišemo ih nakon valjanog zahtjeva, osim podataka koje moramo zadržati zbog zakonske obveze ili pravnih zahtjeva. Istekli kodovi za potvrdu i resetiranje brišu se automatski. Financijska i porezna dokumentacija čuva se onoliko dugo koliko zahtijeva primjenjivo pravo. Sigurnosne kopije uklanjaju se prema ciklusu pružatelja.</p></Section>
    <Section title="7. Sigurnost i povjerljivost poruka"><p>Prijenos se štiti TLS-om, a sadržaj novih poruka i poruka u ponudama šifrira se na aplikacijskoj razini algoritmom AES-256-GCM. Infrastrukturni pružatelj dodatno šifrira pohranu. Ovo nije šifriranje s kraja na kraj: ovlašteni VanScout sustavi mogu dešifrirati sadržaj radi isporuke, podrške, sigurnosti i zakonskih obveza. Pristup razgovoru ograničen je na njegove sudionike i ovlašteno osoblje prema potrebi.</p></Section>
    <Section title="8. Vaša prava"><p>Ovisno o okolnostima imate pravo na informacije, pristup, ispravak, brisanje, ograničenje, prenosivost i prigovor te pravo povući privolu. Kopiju podataka možete preuzeti u profilu, a račun možete izbrisati. Na zahtjev odgovaramo bez nepotrebnog odgađanja, u pravilu unutar mjesec dana. Možete podnijeti pritužbu Agenciji za zaštitu osobnih podataka (AZOP), <a href="https://azop.hr" rel="noreferrer">azop.hr</a>, ili nadležnom tijelu u svojoj državi.</p></Section>
    <Section title="9. Djeca i promjene"><p>VanScout nije namijenjen osobama mlađima od 18 godina. Ovu obavijest mijenjamo kada se promijene obrada, pružatelji ili pravni zahtjevi. Zadnje ažuriranje: 20. rujna 2026.</p></Section>
  </>;
  return <>
    <Section title="1. Controller"><p>The controller is {operator.name}, {operator.address}, registration number {operator.registration}, VAT/tax ID {operator.vatId}. Contact <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a> about privacy or to exercise your rights.</p></Section>
    <Section title="2. Data we process"><p>We process account and identity information, email and verified phone number; transport requests, addresses, coordinates, images and instructions; offers, prices and messages; credit-purchase information and Stripe identifiers; and security and technical logs needed to operate the service. Do not put sensitive information in messages.</p></Section>
    <Section title="3. Purposes and legal bases"><ul><li>accounts, matching customers and carriers, offers, chat and transport fulfilment: performance of a contract or pre-contractual steps;</li><li>accounting, tax and regulatory duties: compliance with legal obligations;</li><li>fraud prevention, security, dispute handling and service reliability: legitimate interests following a necessity and balancing assessment;</li><li>optional marketing or similar activities: consent, if introduced.</li></ul></Section>
    <Section title="4. Visibility and recipients"><p>Participants in a transport see the information needed for the listing, offer and conversation. Contact details are disclosed to the other party after transport confirmation. Providers that may process data include Vercel (hosting), Neon/AWS (database), Ably (realtime notifications), Google and Firebase (identity and phone verification), Stripe (payments), Zoho (email) and Geoapify (location search). An Article 28 processor agreement must be maintained with each applicable processor.</p></Section>
    <Section title="5. International transfers"><p>The production database is hosted in the European Union, and some providers or subprocessors may process data outside the EEA. For those transfers we use an adequacy decision where applicable or Article 46 safeguards, including Standard Contractual Clauses and necessary supplementary measures. You may request a copy of the relevant safeguards from the privacy contact.</p></Section>
    <Section title="6. Retention and deletion"><p>Messages and offer-message text are automatically removed after 730 days. Account data is kept while the account is active and erased after a valid request, except where retention is necessary for a legal obligation or legal claims. Expired verification and reset records are deleted automatically. Financial and tax records are retained for the period required by applicable law. Provider backups expire according to the provider backup cycle.</p></Section>
    <Section title="7. Message security"><p>Transport is protected with TLS, and new chat and offer-message content is encrypted at the application layer using AES-256-GCM. The infrastructure provider also encrypts stored data. This is not end-to-end encryption: authorised VanScout systems can decrypt content for delivery, support, safety and legal obligations. Conversation access is restricted to its participants and authorised personnel where necessary.</p></Section>
    <Section title="8. Your rights"><p>Depending on the circumstances, you have rights to information, access, rectification, erasure, restriction, portability and objection, and to withdraw consent. You can download your data and delete your account from your profile. We respond without undue delay, normally within one month. You may complain to the Croatian Personal Data Protection Agency (AZOP), <a href="https://azop.hr" rel="noreferrer">azop.hr</a>, or your local supervisory authority.</p></Section>
    <Section title="9. Children and changes"><p>VanScout is not intended for anyone under 18. We update this notice when processing, providers or legal requirements change. Last updated: 20 September 2026.</p></Section>
  </>;
}

function Cookies({ language }: { language: Language }) {
  const hr = language === "hr";
  return <>
    <Section title={hr ? "Kolačići i lokalna pohrana" : "Cookies and local storage"}><p>{hr ? "VanScout trenutačno ne koristi analitičke ni oglašivačke kolačiće. Koristimo strogo nužan HttpOnly kolačić vanscout_session za prijavu (do 8 sati) i lokalnu postavku vanscout-language za odabrani jezik. Ti su elementi potrebni za uslugu ili za pamćenje izričite postavke." : "VanScout currently uses no analytics or advertising cookies. We use the strictly necessary HttpOnly vanscout_session cookie for sign-in (up to 8 hours) and the vanscout-language local preference to remember the selected language. These items are necessary for the service or remember an explicitly requested preference."}</p></Section>
    <Section title={hr ? "Vanjske usluge" : "External services"}><p>{hr ? "Google Identity Services i Firebase koriste se samo kada pokrenete prijavu ili potvrdu telefona te mogu postaviti vlastite nužne podatke. Stripe može postaviti kolačiće na svojoj domeni kada otvorite stranicu plaćanja. Prije uvođenja analitike, oglašavanja ili drugih nenužnih tehnologija zatražit ćemo prethodnu privolu i omogućiti povlačenje." : "Google Identity Services and Firebase are used when you start sign-in or phone verification and may set their own necessary storage. Stripe may set cookies on its domain when you open checkout. Before introducing analytics, advertising or other non-essential technologies, we will request prior consent and provide withdrawal controls."}</p></Section>
    <Section title={hr ? "Upravljanje" : "Control"}><p>{hr ? "Kolačiće možete obrisati u postavkama preglednika. Brisanje kolačića sesije odjavljuje vas. Za pitanja se obratite na" : "You can delete cookies in your browser settings. Removing the session cookie signs you out. For questions, contact"} <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a>.</p></Section>
  </>;
}

function Terms({ language }: { language: Language }) {
  const hr = language === "hr";
  return <>
    <Section title={hr ? "Usluga i prihvat" : "Service and acceptance"}><p>{hr ? "Korištenjem VanScouta prihvaćate ove uvjete. Morate imati najmanje 18 godina i dati točne podatke. VanScout pruža internetsko mjesto koje povezuje korisnike i neovisne prijevoznike; ugovor o prijevozu nastaje između tih stranaka kada obje potvrde ponudu, osim ako je izričito navedeno drukčije." : "By using VanScout you accept these terms. You must be at least 18 and provide accurate information. VanScout provides an online venue connecting customers with independent carriers; the transport contract is formed between those parties when both confirm an offer, unless expressly stated otherwise."}</p></Section>
    <Section title={hr ? "Obveze korisnika i prijevoznika" : "Customer and carrier duties"}><p>{hr ? "Korisnici moraju zakonito opisati predmet, adresu, pristup i rizike. Prijevoznici moraju imati potrebne registracije, dozvole, osiguranje, porezni status i sposobnost sigurno izvršiti prijevoz. Zabranjeni su nezakoniti, opasni ili obmanjujući sadržaji, uznemiravanje, zaobilaženje sigurnosti i zlouporaba tuđih podataka." : "Customers must lawfully and accurately describe the item, addresses, access and risks. Carriers must maintain required registrations, licences, insurance, tax status and ability to perform transport safely. Illegal, dangerous or misleading content, harassment, security circumvention and misuse of another person's data are prohibited."}</p></Section>
    <Section title={hr ? "Cijene, krediti i plaćanje" : "Prices, credits and payment"}><p>{hr ? "Prijevoznik određuje cijenu ponude i navodi uključuje li PDV. Krediti se kupuju putem Stripea. Kada obje strane potvrde prijevoz, s računa prijevoznika jednom se odbija provizija prikazana prije potvrde. Zakonska prava potrošača i obvezni povrati ne mogu se isključiti ovim uvjetima." : "The carrier sets the offer price and states whether VAT is included. Credits are purchased through Stripe. When both parties confirm transport, the displayed commission is deducted once from the carrier's credit balance. Mandatory consumer rights and legally required refunds are not excluded by these terms."}</p></Section>
    <Section title={hr ? "Sadržaj, sigurnost i prekid" : "Content, safety and termination"}><p>{hr ? "Zadržavate prava na svoj sadržaj i dajete VanScoutu ograničenu dozvolu za njegovu pohranu, prikaz i obradu radi pružanja i zaštite usluge. Možemo ograničiti ili ukloniti nezakonit sadržaj i suspendirati račun zbog prijevare, sigurnosnog rizika ili bitne povrede, uz obrazloženje i mogućnost prigovora kada zakon to zahtijeva." : "You retain rights in your content and grant VanScout a limited licence to store, display and process it to provide and protect the service. We may restrict or remove illegal content and suspend an account for fraud, safety risk or material breach, with reasons and complaint options where required by law."}</p></Section>
    <Section title={hr ? "Odgovornost i pravo" : "Liability and law"}><p>{hr ? "Ništa u ovim uvjetima ne ograničava odgovornost ili prava koja se po zakonu ne mogu ograničiti. Za potrošače vrijede obvezna pravila njihove države prebivališta. Za ostalo se primjenjuje hrvatsko pravo, a nadležnost se određuje prema obveznim pravilima. Za prigovor se obratite na" : "Nothing in these terms limits liability or rights that cannot legally be limited. Consumers retain mandatory protections of their country of residence. Otherwise Croatian law applies and jurisdiction follows mandatory rules. For complaints contact"} <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a>.</p></Section>
  </>;
}

function Impressum({ language }: { language: Language }) {
  const hr = language === "hr";
  return <>
    <Section title={hr ? "Podaci o operatoru" : "Operator information"}><dl><dt>{hr ? "Naziv" : "Legal name"}</dt><dd>{operator.name}</dd><dt>{hr ? "Sjedište" : "Registered address"}</dt><dd>{operator.address}</dd><dt>{hr ? "Registracija" : "Registration"}</dt><dd>{operator.registration}</dd><dt>OIB / VAT ID</dt><dd>{operator.vatId}</dd><dt>Email</dt><dd><a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a></dd></dl></Section>
    <Section title={hr ? "Nadzor" : "Supervision"}><p>{hr ? "Nadležni sud, regulator, osoba ovlaštena za zastupanje i podaci registra moraju se dodati prema pravnom obliku operatora prije javnog pokretanja usluge." : "The competent court, regulator, authorised representative and register details must be added as required by the operator's legal form before public launch."}</p></Section>
  </>;
}

export function LegalDocumentContent({ document, language }: { document: LegalDocument; language: Language }) {
  return <div className="legal-policy">
    {document === "privacy" ? <Privacy language={language} /> : document === "cookies" ? <Cookies language={language} /> : document === "terms" ? <Terms language={language} /> : <Impressum language={language} />}
  </div>;
}
